/**
 * Bộ bài học theo chủ đề, tổ chức giống cách Tsunagaru (tsunagarujp.mext.go.jp)
 * trình bày: mỗi bài là một cảnh đời sống, có mục tiêu "làm được gì", một đoạn
 * hội thoại của cảnh đó và bảng từ vựng đi kèm. Cùng một chủ đề có thể có bài ở
 * nhiều cấp độ (ví dụ đi khám bệnh N4 chỉ nói triệu chứng, N3 kể bệnh sử).
 *
 * Phân bố: N5 8 bài · N4 6 · N3 4 · N2 2. Chưa có bài N1 — hội thoại đời sống ở
 * N1 thiếu tự nhiên, N1 thiên về văn viết.
 *
 * ⚠️ Nội dung tiếng Nhật ở đây do Claude soạn và CHƯA được người biết tiếng Nhật
 * rà soát. Phải rà lại trước khi dùng trong bản bảo vệ hoặc demo chính thức.
 *
 * `title` là khoá tự nhiên để upsert: đổi tiêu đề một bài đã có sẽ tạo bài mới
 * và làm mất tiến độ học gắn với `_id` cũ.
 *
 * Dữ liệu thuần, không chạm DB — `seed-situational-lessons.js` lo phần ghi.
 */

const turn = (speaker, textJa, reading, textVi) => ({
  speaker,
  text_ja: textJa,
  reading,
  text_vi: textVi,
});

const word = (w, hiragana, meaning) => ({ word: w, hiragana, meaning });

export const SITUATIONAL_LESSONS = [
  // ───────────────────────────── N5 ─────────────────────────────
  {
    title: 'Tình huống: Tự giới thiệu',
    level: 'N5',
    order: 1,
    situation: 'self_introduction',
    type: 'Tình huống',
    description: 'Chào hỏi và giới thiệu bản thân khi gặp một người lần đầu.',
    can_do_goals: [
      'Chào hỏi lịch sự khi gặp ai đó lần đầu',
      'Nói được tên và đất nước của mình',
      'Hỏi được nghề nghiệp của người đối diện',
    ],
    dialogue: [
      turn('Linh', 'はじめまして。リンです。ベトナムから来ました。', 'はじめまして。リンです。ベトナムからきました。', 'Rất vui được gặp anh. Tôi là Linh. Tôi đến từ Việt Nam.'),
      turn('Tanaka', 'はじめまして。田中です。どうぞよろしくお願いします。', 'はじめまして。たなかです。どうぞよろしくおねがいします。', 'Rất vui được gặp chị. Tôi là Tanaka. Rất mong được giúp đỡ.'),
      turn('Linh', 'よろしくお願いします。田中さんのお仕事は何ですか。', 'よろしくおねがいします。たなかさんのおしごとはなんですか。', 'Rất mong được giúp đỡ. Anh Tanaka làm nghề gì ạ?'),
      turn('Tanaka', '会社員です。リンさんは？', 'かいしゃいんです。リンさんは？', 'Tôi là nhân viên công ty. Còn chị Linh?'),
      turn('Linh', '学生です。今、日本語を勉強しています。', 'がくせいです。いま、にほんごをべんきょうしています。', 'Tôi là sinh viên. Hiện tôi đang học tiếng Nhật.'),
      turn('Tanaka', 'そうですか。がんばってください。', 'そうですか。がんばってください。', 'Vậy à. Chị cố gắng nhé.'),
    ],
    vocabularies: [
      word('名前', 'なまえ', 'tên'),
      word('国', 'くに', 'đất nước'),
      word('仕事', 'しごと', 'công việc'),
      word('会社員', 'かいしゃいん', 'nhân viên công ty'),
      word('学生', 'がくせい', 'học sinh, sinh viên'),
      word('先生', 'せんせい', 'giáo viên'),
      word('友達', 'ともだち', 'bạn bè'),
      word('勉強', 'べんきょう', 'việc học'),
      word('私', 'わたし', 'tôi'),
      word('出身', 'しゅっしん', 'quê quán, xuất thân'),
      word('日本人', 'にほんじん', 'người Nhật'),
    ],
  },
  {
    title: 'Tình huống: Sinh hoạt hằng ngày',
    level: 'N5',
    order: 2,
    situation: 'daily_life',
    type: 'Tình huống',
    description: 'Kể về giờ giấc và các việc làm quen thuộc trong một ngày.',
    can_do_goals: [
      'Nói được giờ thức dậy và giờ đi ngủ',
      'Kể được những việc mình làm mỗi sáng',
      'Hỏi được thói quen hằng ngày của người khác',
    ],
    dialogue: [
      turn('Mai', '毎朝、何時に起きますか。', 'まいあさ、なんじにおきますか。', 'Mỗi sáng bạn dậy lúc mấy giờ?'),
      turn('Kenta', '６時に起きます。', 'ろくじにおきます。', 'Mình dậy lúc 6 giờ.'),
      turn('Mai', '早いですね。朝ごはんを食べますか。', 'はやいですね。あさごはんをたべますか。', 'Sớm nhỉ. Bạn có ăn sáng không?'),
      turn('Kenta', 'はい、パンを食べて、コーヒーを飲みます。', 'はい、パンをたべて、コーヒーをのみます。', 'Có, mình ăn bánh mì rồi uống cà phê.'),
      turn('Mai', '私は７時半に起きます。', 'わたしはしちじはんにおきます。', 'Mình thì dậy lúc 7 rưỡi.'),
      turn('Kenta', '夜は何時に寝ますか。', 'よるはなんじにねますか。', 'Buổi tối bạn đi ngủ lúc mấy giờ?'),
      turn('Mai', '１２時ごろ寝ます。', 'じゅうにじごろねます。', 'Mình ngủ khoảng 12 giờ.'),
    ],
    vocabularies: [
      word('起きる', 'おきる', 'thức dậy'),
      word('寝る', 'ねる', 'ngủ'),
      word('毎朝', 'まいあさ', 'mỗi sáng'),
      word('朝ごはん', 'あさごはん', 'bữa sáng'),
      word('食べる', 'たべる', 'ăn'),
      word('飲む', 'のむ', 'uống'),
      word('早い', 'はやい', 'sớm, nhanh'),
      word('夜', 'よる', 'buổi tối, ban đêm'),
      word('朝', 'あさ', 'buổi sáng'),
      word('毎日', 'まいにち', 'hằng ngày'),
      word('行く', 'いく', 'đi'),
      word('帰る', 'かえる', 'trở về, về nhà'),
    ],
  },
  {
    title: 'Tình huống: Đi siêu thị',
    level: 'N5',
    order: 3,
    situation: 'supermarket',
    type: 'Tình huống',
    description: 'Hỏi giá, hỏi vị trí hàng hoá và thanh toán ở siêu thị.',
    can_do_goals: [
      'Hỏi được giá của một món hàng',
      'Hỏi được món hàng nằm ở đâu trong siêu thị',
      'Trả lời được khi nhân viên hỏi có cần túi không',
    ],
    dialogue: [
      turn('Khách', 'すみません、牛乳はどこですか。', 'すみません、ぎゅうにゅうはどこですか。', 'Xin lỗi, sữa tươi ở đâu ạ?'),
      turn('Nhân viên', 'あちらの右のたなです。', 'あちらのみぎのたなです。', 'Ở kệ bên phải đằng kia ạ.'),
      turn('Khách', 'ありがとうございます。これはいくらですか。', 'ありがとうございます。これはいくらですか。', 'Cảm ơn chị. Cái này bao nhiêu tiền ạ?'),
      turn('Nhân viên', '２００円です。', 'にひゃくえんです。', '200 yên ạ.'),
      turn('Nhân viên', 'ふくろはいりますか。', 'ふくろはいりますか。', 'Anh/chị có cần túi không ạ?'),
      turn('Khách', 'いいえ、けっこうです。', 'いいえ、けっこうです。', 'Không, không cần đâu ạ.'),
      turn('Nhân viên', 'ありがとうございました。', 'ありがとうございました。', 'Xin cảm ơn quý khách.'),
    ],
    vocabularies: [
      word('牛乳', 'ぎゅうにゅう', 'sữa tươi'),
      word('店員', 'てんいん', 'nhân viên cửa hàng'),
      word('棚', 'たな', 'kệ hàng'),
      word('袋', 'ふくろ', 'túi đựng'),
      word('値段', 'ねだん', 'giá cả'),
      word('会計', 'かいけい', 'thanh toán, tính tiền'),
      word('野菜', 'やさい', 'rau củ'),
      word('肉', 'にく', 'thịt'),
      word('卵', 'たまご', 'trứng'),
    ],
  },
  {
    title: 'Tình huống: Ở cửa hàng tiện lợi',
    level: 'N5',
    order: 4,
    situation: 'convenience_store',
    type: 'Tình huống',
    description: 'Mua cơm hộp, trả lời các câu hỏi quen thuộc của nhân viên thu ngân.',
    can_do_goals: [
      'Trả lời được khi nhân viên hỏi có hâm nóng cơm hộp không',
      'Xin được đũa khi mua đồ ăn',
      'Hỏi được có trả bằng thẻ được không',
    ],
    dialogue: [
      turn('Nhân viên', 'いらっしゃいませ。お弁当、温めますか。', 'いらっしゃいませ。おべんとう、あたためますか。', 'Kính chào quý khách. Cơm hộp có cần hâm nóng không ạ?'),
      turn('Khách', 'はい、お願いします。', 'はい、おねがいします。', 'Vâng, nhờ chị.'),
      turn('Nhân viên', 'お箸はいりますか。', 'おはしはいりますか。', 'Quý khách có cần đũa không ạ?'),
      turn('Khách', 'はい、一つください。', 'はい、ひとつください。', 'Có, cho tôi một đôi.'),
      turn('Nhân viên', '全部で６５０円です。', 'ぜんぶでろっぴゃくごじゅうえんです。', 'Tất cả là 650 yên ạ.'),
      turn('Khách', 'カードで払えますか。', 'カードではらえますか。', 'Tôi trả bằng thẻ được không?'),
      turn('Nhân viên', 'はい、大丈夫です。こちらにどうぞ。', 'はい、だいじょうぶです。こちらにどうぞ。', 'Vâng, được ạ. Mời quý khách quẹt ở đây.'),
    ],
    vocabularies: [
      word('弁当', 'べんとう', 'cơm hộp'),
      word('温める', 'あたためる', 'hâm nóng'),
      word('箸', 'はし', 'đũa'),
      word('全部', 'ぜんぶ', 'tất cả'),
      word('払う', 'はらう', 'trả tiền'),
      word('大丈夫', 'だいじょうぶ', 'ổn, không sao'),
      word('一つ', 'ひとつ', 'một cái'),
      word('コンビニ', 'コンビニ', 'cửa hàng tiện lợi'),
    ],
  },
  {
    title: 'Tình huống: Đi tàu',
    level: 'N5',
    order: 5,
    situation: 'train',
    type: 'Tình huống',
    description: 'Mua vé, hỏi đường ra ga và hỏi tàu đi đúng tuyến.',
    can_do_goals: [
      'Hỏi được tàu nào đi đến nơi mình muốn',
      'Hỏi được giá vé và mua vé',
      'Hỏi được tàu khởi hành ở sân ga số mấy',
    ],
    dialogue: [
      turn('Khách', 'すみません、東京駅までいくらですか。', 'すみません、とうきょうえきまでいくらですか。', 'Xin lỗi, đến ga Tokyo hết bao nhiêu tiền ạ?'),
      turn('Nhân viên', '４５０円です。', 'よんひゃくごじゅうえんです。', '450 yên ạ.'),
      turn('Khách', 'きっぷを１まいください。', 'きっぷをいちまいください。', 'Cho tôi một vé ạ.'),
      turn('Khách', 'この電車は東京駅に行きますか。', 'このでんしゃはとうきょうえきにいきますか。', 'Tàu này có đi ga Tokyo không ạ?'),
      turn('Nhân viên', 'はい、行きます。３ばんせんです。', 'はい、いきます。さんばんせんです。', 'Có ạ. Sân ga số 3 ạ.'),
      turn('Khách', 'わかりました。ありがとうございます。', 'わかりました。ありがとうございます。', 'Tôi hiểu rồi. Cảm ơn anh/chị.'),
    ],
    vocabularies: [
      word('電車', 'でんしゃ', 'tàu điện'),
      word('駅', 'えき', 'nhà ga'),
      word('切符', 'きっぷ', 'vé'),
      word('改札', 'かいさつ', 'cửa soát vé'),
      word('乗り換え', 'のりかえ', 'chuyển tàu'),
      word('片道', 'かたみち', 'một chiều'),
      word('往復', 'おうふく', 'khứ hồi'),
      word('時刻表', 'じこくひょう', 'bảng giờ tàu'),
    ],
  },
  {
    title: 'Tình huống: Ở nhà hàng',
    level: 'N5',
    order: 6,
    situation: 'restaurant',
    type: 'Tình huống',
    description: 'Gọi món, hỏi món ăn và thanh toán ở nhà hàng.',
    can_do_goals: [
      'Gọi được món mình muốn ăn',
      'Hỏi được món nào ngon hoặc món nào không cay',
      'Xin được hoá đơn khi ăn xong',
    ],
    dialogue: [
      turn('Nhân viên', 'いらっしゃいませ。何名さまですか。', 'いらっしゃいませ。なんめいさまですか。', 'Kính chào quý khách. Quý khách đi mấy người ạ?'),
      turn('Khách', '２人です。', 'ふたりです。', 'Hai người ạ.'),
      turn('Khách', 'すみません、ちゅうもんをおねがいします。', 'すみません、ちゅうもんをおねがいします。', 'Xin lỗi, cho tôi gọi món ạ.'),
      turn('Khách', 'ラーメンを１つとおちゃをください。', 'ラーメンをひとつとおちゃをください。', 'Cho tôi một tô ramen và trà ạ.'),
      turn('Nhân viên', 'かしこまりました。少々おまちください。', 'かしこまりました。しょうしょうおまちください。', 'Vâng ạ. Quý khách vui lòng đợi một chút.'),
      turn('Khách', 'すみません、おかいけいをおねがいします。', 'すみません、おかいけいをおねがいします。', 'Xin lỗi, cho tôi thanh toán ạ.'),
    ],
    vocabularies: [
      word('注文', 'ちゅうもん', 'gọi món, đặt hàng'),
      word('料理', 'りょうり', 'món ăn'),
      word('飲み物', 'のみもの', 'đồ uống'),
      word('お茶', 'おちゃ', 'trà'),
      word('水', 'みず', 'nước'),
      word('辛い', 'からい', 'cay'),
      word('美味しい', 'おいしい', 'ngon'),
      word('店', 'みせ', 'quán, cửa hàng'),
      word('席', 'せき', 'chỗ ngồi'),
    ],
  },
  {
    title: 'Tình huống: Ở bưu điện',
    level: 'N5',
    order: 7,
    situation: 'post_office',
    type: 'Tình huống',
    description: 'Gửi bưu kiện về nước, chọn cách gửi và điền địa chỉ.',
    can_do_goals: [
      'Nói được mình muốn gửi đồ đi đâu',
      'Hỏi được giá và thời gian gửi',
      'Điền được địa chỉ theo hướng dẫn của nhân viên',
    ],
    dialogue: [
      turn('Khách', 'すみません、この荷物をベトナムに送りたいです。', 'すみません、このにもつをベトナムにおくりたいです。', 'Xin lỗi, tôi muốn gửi kiện hàng này về Việt Nam.'),
      turn('Nhân viên', '船便と航空便がありますが、どちらにしますか。', 'ふなびんとこうくうびんがありますが、どちらにしますか。', 'Có gửi đường biển và đường hàng không, quý khách chọn cách nào ạ?'),
      turn('Khách', '航空便はいくらですか。', 'こうくうびんはいくらですか。', 'Gửi đường hàng không hết bao nhiêu tiền ạ?'),
      turn('Nhân viên', '３２００円です。一週間ぐらいで着きます。', 'さんぜんにひゃくえんです。いっしゅうかんぐらいでつきます。', '3.200 yên ạ. Khoảng một tuần là tới nơi.'),
      turn('Khách', 'じゃあ、航空便でお願いします。', 'じゃあ、こうくうびんでおねがいします。', 'Vậy cho tôi gửi đường hàng không.'),
      turn('Nhân viên', 'では、この紙に住所を書いてください。', 'では、このかみにじゅうしょをかいてください。', 'Vậy quý khách vui lòng viết địa chỉ vào tờ giấy này.'),
    ],
    vocabularies: [
      word('郵便局', 'ゆうびんきょく', 'bưu điện'),
      word('荷物', 'にもつ', 'hành lý, bưu kiện'),
      word('送る', 'おくる', 'gửi'),
      word('航空便', 'こうくうびん', 'gửi đường hàng không'),
      word('船便', 'ふなびん', 'gửi đường biển'),
      word('住所', 'じゅうしょ', 'địa chỉ'),
      word('切手', 'きって', 'tem thư'),
      word('手紙', 'てがみ', 'thư'),
    ],
  },
  {
    title: 'Tình huống: Ở trường học',
    level: 'N5',
    order: 8,
    situation: 'school',
    type: 'Tình huống',
    description: 'Hỏi giáo viên khi chưa hiểu bài và hỏi hạn nộp bài tập.',
    can_do_goals: [
      'Xin phép hỏi giáo viên khi chưa hiểu',
      'Hỏi được nghĩa của một từ',
      'Hỏi được hạn nộp bài tập về nhà',
    ],
    dialogue: [
      turn('Học sinh', '先生、すみません。質問があります。', 'せんせい、すみません。しつもんがあります。', 'Thưa cô, em xin lỗi. Em có câu hỏi ạ.'),
      turn('Giáo viên', 'はい、何ですか。', 'はい、なんですか。', 'Ừ, em hỏi gì?'),
      turn('Học sinh', 'この言葉の意味が分かりません。', 'このことばのいみがわかりません。', 'Em không hiểu nghĩa của từ này ạ.'),
      turn('Giáo viên', 'それは「宿題」です。家でする勉強のことです。', 'それは「しゅくだい」です。いえでするべんきょうのことです。', 'Đó là "bài tập về nhà". Là phần học làm ở nhà.'),
      turn('Học sinh', 'ああ、分かりました。宿題はいつまでですか。', 'ああ、わかりました。しゅくだいはいつまでですか。', 'À, em hiểu rồi. Bài tập nộp đến khi nào ạ?'),
      turn('Giáo viên', '金曜日までに出してください。', 'きんようびまでにだしてください。', 'Các em nộp trước thứ Sáu nhé.'),
      turn('Học sinh', 'はい、ありがとうございます。', 'はい、ありがとうございます。', 'Vâng, em cảm ơn cô ạ.'),
    ],
    vocabularies: [
      word('質問', 'しつもん', 'câu hỏi'),
      word('言葉', 'ことば', 'từ ngữ'),
      word('意味', 'いみ', 'ý nghĩa'),
      word('宿題', 'しゅくだい', 'bài tập về nhà'),
      word('教室', 'きょうしつ', 'phòng học'),
      word('出す', 'だす', 'nộp, đưa ra'),
      word('分かる', 'わかる', 'hiểu'),
      word('金曜日', 'きんようび', 'thứ Sáu'),
    ],
  },

  // ───────────────────────────── N4 ─────────────────────────────
  {
    title: 'Tình huống: Đi xe buýt',
    level: 'N4',
    order: 1,
    situation: 'bus',
    type: 'Tình huống',
    description: 'Hỏi tuyến xe buýt, vị trí trạm và cách trả tiền vé.',
    can_do_goals: [
      'Hỏi được xe buýt có đi đến nơi mình cần không',
      'Hỏi được trạm xe buýt nằm ở đâu',
      'Biết được khi nào phải trả tiền vé',
    ],
    dialogue: [
      turn('Khách', 'すみません、このバスは市役所へ行きますか。', 'すみません、このバスはしやくしょへいきますか。', 'Xin lỗi, xe buýt này có đi đến toà thị chính không ạ?'),
      turn('Tài xế', 'いいえ、行きません。３番のバスに乗ってください。', 'いいえ、いきません。さんばんのバスにのってください。', 'Không, không đi đâu. Anh/chị hãy lên xe số 3.'),
      turn('Khách', '３番のバス停はどこにありますか。', 'さんばんのバスていはどこにありますか。', 'Trạm của xe số 3 ở đâu ạ?'),
      turn('Tài xế', '道の向こう側にありますよ。', 'みちのむこうがわにありますよ。', 'Ở phía bên kia đường đấy.'),
      turn('Khách', '料金は乗る時に払いますか。', 'りょうきんはのるときにはらいますか。', 'Tiền vé thì trả lúc lên xe ạ?'),
      turn('Tài xế', 'いいえ、降りる時に払ってください。', 'いいえ、おりるときにはらってください。', 'Không, trả lúc xuống xe nhé.'),
      turn('Khách', '分かりました。ありがとうございます。', 'わかりました。ありがとうございます。', 'Tôi hiểu rồi. Cảm ơn anh.'),
    ],
    vocabularies: [
      word('バス停', 'バスてい', 'trạm xe buýt'),
      word('運転手', 'うんてんしゅ', 'tài xế'),
      word('乗る', 'のる', 'lên xe, đi (xe)'),
      word('降りる', 'おりる', 'xuống xe'),
      word('料金', 'りょうきん', 'giá vé, phí'),
      word('向こう', 'むこう', 'phía bên kia'),
      word('次', 'つぎ', 'tiếp theo'),
      word('道', 'みち', 'con đường'),
    ],
  },
  {
    title: 'Tình huống: Ở hiệu thuốc',
    level: 'N4',
    order: 2,
    situation: 'pharmacy',
    type: 'Tình huống',
    description: 'Mô tả triệu chứng cảm cúm và hỏi cách dùng thuốc.',
    can_do_goals: [
      'Mô tả được các triệu chứng đơn giản',
      'Hiểu được cách uống thuốc dược sĩ dặn',
      'Hỏi được thuốc có gây buồn ngủ không',
    ],
    dialogue: [
      turn('Dược sĩ', 'どうしましたか。', 'どうしましたか。', 'Anh/chị bị làm sao ạ?'),
      turn('Khách', '昨日から喉が痛くて、少し熱があります。', 'きのうからのどがいたくて、すこしねつがあります。', 'Từ hôm qua tôi bị đau họng và hơi sốt.'),
      turn('Dược sĩ', '咳は出ますか。', 'せきはでますか。', 'Anh/chị có bị ho không?'),
      turn('Khách', 'はい、夜になると咳が出ます。', 'はい、よるになるとせきがでます。', 'Có, cứ tối là tôi bị ho.'),
      turn('Dược sĩ', 'では、この薬を一日三回、食後に飲んでください。', 'では、このくすりをいちにちさんかい、しょくごにのんでください。', 'Vậy anh/chị uống thuốc này ngày ba lần, sau bữa ăn nhé.'),
      turn('Khách', 'この薬を飲むと、眠くなりますか。', 'このくすりをのむと、ねむくなりますか。', 'Uống thuốc này có bị buồn ngủ không ạ?'),
      turn('Dược sĩ', '少し眠くなるかもしれないので、運転はしないでください。', 'すこしねむくなるかもしれないので、うんてんはしないでください。', 'Có thể hơi buồn ngủ, nên anh/chị đừng lái xe nhé.'),
    ],
    vocabularies: [
      word('薬', 'くすり', 'thuốc'),
      word('喉', 'のど', 'họng'),
      word('熱', 'ねつ', 'sốt'),
      word('咳', 'せき', 'ho'),
      word('食後', 'しょくご', 'sau bữa ăn'),
      word('眠い', 'ねむい', 'buồn ngủ'),
      word('痛い', 'いたい', 'đau'),
      word('風邪', 'かぜ', 'cảm lạnh'),
    ],
  },
  {
    title: 'Tình huống: Đi khám bệnh',
    level: 'N4',
    order: 3,
    situation: 'hospital',
    type: 'Tình huống',
    description: 'Làm thủ tục ở quầy tiếp nhận và nói chỗ đau với bác sĩ.',
    can_do_goals: [
      'Xuất trình thẻ bảo hiểm và điền phiếu khai bệnh',
      'Nói được chỗ đau và bắt đầu đau từ khi nào',
      'Hiểu được khi bác sĩ đề nghị xét nghiệm',
    ],
    dialogue: [
      turn('Lễ tân', '保険証はお持ちですか。', 'ほけんしょうはおもちですか。', 'Anh/chị có mang thẻ bảo hiểm không ạ?'),
      turn('Bệnh nhân', 'はい、これです。', 'はい、これです。', 'Có, đây ạ.'),
      turn('Lễ tân', '今日はどうされましたか。', 'きょうはどうされましたか。', 'Hôm nay anh/chị bị làm sao ạ?'),
      turn('Bệnh nhân', '三日前からお腹が痛いんです。', 'みっかまえからおなかがいたいんです。', 'Tôi bị đau bụng từ ba ngày trước.'),
      turn('Lễ tân', 'では、この問診票に書いて、少々お待ちください。', 'では、このもんしんひょうにかいて、しょうしょうおまちください。', 'Vậy anh/chị điền vào phiếu khai bệnh này và đợi một chút nhé.'),
      turn('Bác sĩ', 'どこが痛いですか。', 'どこがいたいですか。', 'Đau ở chỗ nào?'),
      turn('Bệnh nhân', 'ここです。食べると痛くなります。', 'ここです。たべるといたくなります。', 'Ở đây ạ. Cứ ăn vào là đau.'),
      turn('Bác sĩ', '分かりました。検査をしましょう。', 'わかりました。けんさをしましょう。', 'Tôi hiểu rồi. Mình làm xét nghiệm nhé.'),
    ],
    vocabularies: [
      word('病院', 'びょういん', 'bệnh viện'),
      word('保険証', 'ほけんしょう', 'thẻ bảo hiểm y tế'),
      word('受付', 'うけつけ', 'quầy tiếp nhận'),
      word('患者', 'かんじゃ', 'bệnh nhân'),
      word('お腹', 'おなか', 'bụng'),
      word('問診票', 'もんしんひょう', 'phiếu khai bệnh'),
      word('検査', 'けんさ', 'xét nghiệm, kiểm tra'),
      word('医者', 'いしゃ', 'bác sĩ'),
    ],
  },
  {
    title: 'Tình huống: Mở tài khoản ngân hàng',
    level: 'N4',
    order: 4,
    situation: 'bank',
    type: 'Tình huống',
    description: 'Mở tài khoản, chuẩn bị giấy tờ và hỏi thời gian nhận thẻ.',
    can_do_goals: [
      'Nói được mình muốn mở tài khoản',
      'Chuẩn bị đúng giấy tờ cần mang theo',
      'Hỏi được khi nào nhận được thẻ rút tiền',
    ],
    dialogue: [
      turn('Khách', '口座を作りたいんですが。', 'こうざをつくりたいんですが。', 'Tôi muốn mở tài khoản ạ.'),
      turn('Nhân viên', 'かしこまりました。在留カードと印鑑はお持ちですか。', 'かしこまりました。ざいりゅうカードといんかんはおもちですか。', 'Vâng ạ. Quý khách có mang thẻ cư trú và con dấu không ạ?'),
      turn('Khách', '在留カードはありますが、印鑑はありません。', 'ざいりゅうカードはありますが、いんかんはありません。', 'Tôi có thẻ cư trú, nhưng không có con dấu.'),
      turn('Nhân viên', 'サインでも大丈夫です。こちらの用紙に記入してください。', 'サインでもだいじょうぶです。こちらのようしにきにゅうしてください。', 'Ký tên cũng được ạ. Quý khách điền vào mẫu giấy này nhé.'),
      turn('Khách', 'キャッシュカードはいつもらえますか。', 'キャッシュカードはいつもらえますか。', 'Khi nào tôi nhận được thẻ rút tiền ạ?'),
      turn('Nhân viên', '一週間ほどで、ご自宅に届きます。', 'いっしゅうかんほどで、ごじたくにとどきます。', 'Khoảng một tuần, thẻ sẽ được gửi về nhà quý khách.'),
    ],
    vocabularies: [
      word('銀行', 'ぎんこう', 'ngân hàng'),
      word('口座', 'こうざ', 'tài khoản'),
      word('在留カード', 'ざいりゅうカード', 'thẻ cư trú'),
      word('印鑑', 'いんかん', 'con dấu cá nhân'),
      word('用紙', 'ようし', 'mẫu giấy'),
      word('記入', 'きにゅう', 'điền (thông tin)'),
      word('届く', 'とどく', 'được gửi tới'),
      word('暗証番号', 'あんしょうばんごう', 'mã PIN'),
    ],
  },
  {
    title: 'Tình huống: Gọi điện đặt lịch hẹn',
    level: 'N4',
    order: 5,
    situation: 'phone_call',
    type: 'Tình huống',
    description: 'Gọi điện cho tiệm làm tóc để đặt lịch theo ngày giờ mong muốn.',
    can_do_goals: [
      'Mở đầu cuộc gọi đúng cách',
      'Đặt được lịch hẹn theo ngày giờ mình muốn',
      'Để lại tên khi đặt lịch',
    ],
    dialogue: [
      turn('Nhân viên', 'お電話ありがとうございます。さくら美容院です。', 'おでんわありがとうございます。さくらびよういんです。', 'Cảm ơn quý khách đã gọi. Đây là tiệm làm tóc Sakura.'),
      turn('Khách', 'もしもし、予約をしたいんですが。', 'もしもし、よやくをしたいんですが。', 'A lô, tôi muốn đặt lịch ạ.'),
      turn('Nhân viên', 'いつがよろしいですか。', 'いつがよろしいですか。', 'Quý khách muốn hẹn khi nào ạ?'),
      turn('Khách', '土曜日の午後は空いていますか。', 'どようびのごごはあいていますか。', 'Chiều thứ Bảy còn trống không ạ?'),
      turn('Nhân viên', '土曜日は３時なら大丈夫です。', 'どようびはさんじならだいじょうぶです。', 'Thứ Bảy thì 3 giờ được ạ.'),
      turn('Khách', 'じゃあ、３時にお願いします。名前はグエンです。', 'じゃあ、さんじにおねがいします。なまえはグエンです。', 'Vậy cho tôi hẹn 3 giờ. Tôi tên là Nguyễn.'),
      turn('Nhân viên', 'グエン様ですね。お待ちしております。', 'グエンさまですね。おまちしております。', 'Quý khách Nguyễn ạ. Chúng tôi xin đợi quý khách.'),
    ],
    vocabularies: [
      word('電話', 'でんわ', 'điện thoại'),
      word('予約', 'よやく', 'đặt trước, đặt lịch'),
      word('午後', 'ごご', 'buổi chiều'),
      word('空く', 'あく', 'trống, rảnh'),
      word('美容院', 'びよういん', 'tiệm làm tóc'),
      word('土曜日', 'どようび', 'thứ Bảy'),
      word('都合', 'つごう', 'sự thuận tiện (về thời gian)'),
      word('番号', 'ばんごう', 'số (điện thoại, thứ tự)'),
    ],
  },
  {
    title: 'Tình huống: Ngày đầu đi làm thêm',
    level: 'N4',
    order: 6,
    situation: 'part_time_job',
    type: 'Tình huống',
    description: 'Nhận việc từ quản lý, hỏi thứ tự công việc và giờ nghỉ.',
    can_do_goals: [
      'Hỏi được mình cần làm việc gì',
      'Xác nhận được việc tiếp theo sau khi xong một việc',
      'Hỏi được giờ nghỉ giải lao',
    ],
    dialogue: [
      turn('Quản lý', '今日からよろしくお願いします。', 'きょうからよろしくおねがいします。', 'Từ hôm nay mong em làm tốt nhé.'),
      turn('Nhân viên mới', 'よろしくお願いします。何をすればいいですか。', 'よろしくおねがいします。なにをすればいいですか。', 'Em mong được chỉ bảo ạ. Em nên làm gì ạ?'),
      turn('Quản lý', 'まず、この棚に商品を並べてください。', 'まず、このたなにしょうひんをならべてください。', 'Trước hết, em xếp hàng lên kệ này nhé.'),
      turn('Nhân viên mới', '分かりました。終わったら、どうしますか。', 'わかりました。おわったら、どうしますか。', 'Em hiểu rồi. Xong việc đó thì em làm gì tiếp ạ?'),
      turn('Quản lý', '終わったら、レジの使い方を教えます。', 'おわったら、レジのつかいかたをおしえます。', 'Xong thì anh sẽ chỉ em cách dùng máy tính tiền.'),
      turn('Nhân viên mới', '休憩は何時からですか。', 'きゅうけいはなんじからですか。', 'Giờ nghỉ bắt đầu từ mấy giờ ạ?'),
      turn('Quản lý', '１２時から１時間です。', 'じゅうにじからいちじかんです。', 'Từ 12 giờ, nghỉ một tiếng.'),
    ],
    vocabularies: [
      word('店長', 'てんちょう', 'quản lý cửa hàng'),
      word('商品', 'しょうひん', 'hàng hoá'),
      word('並べる', 'ならべる', 'xếp, bày'),
      word('休憩', 'きゅうけい', 'nghỉ giải lao'),
      word('使い方', 'つかいかた', 'cách sử dụng'),
      word('教える', 'おしえる', 'dạy, chỉ bảo'),
      word('給料', 'きゅうりょう', 'tiền lương'),
      word('アルバイト', 'アルバイト', 'việc làm thêm'),
    ],
  },

  // ───────────────────────────── N3 ─────────────────────────────
  {
    title: 'Tình huống: Làm thủ tục chuyển nơi ở',
    level: 'N3',
    order: 1,
    situation: 'city_hall',
    type: 'Tình huống',
    description: 'Khai báo chuyển đến ở toà thị chính và hỏi quầy làm thủ tục bảo hiểm.',
    can_do_goals: [
      'Trình bày được mục đích làm thủ tục',
      'Chuẩn bị đúng giấy tờ khi chuyển nơi ở',
      'Hỏi được quầy xử lý một thủ tục khác',
    ],
    dialogue: [
      turn('Người dân', 'すみません、引っ越してきたので、住所変更の手続きをしたいのですが。', 'すみません、ひっこしてきたので、じゅうしょへんこうのてつづきをしたいのですが。', 'Xin lỗi, tôi mới chuyển nhà đến nên muốn làm thủ tục đổi địa chỉ ạ.'),
      turn('Cán bộ', '転入届ですね。前の市役所でもらった転出証明書はお持ちですか。', 'てんにゅうとどけですね。まえのしやくしょでもらったてんしゅつしょうめいしょはおもちですか。', 'Là khai báo chuyển đến nhỉ. Anh/chị có mang giấy chứng nhận chuyển đi lấy ở toà thị chính cũ không?'),
      turn('Người dân', 'はい、持ってきました。', 'はい、もってきました。', 'Có, tôi có mang theo.'),
      turn('Cán bộ', 'では、この書類に新しい住所を記入して、在留カードと一緒に出してください。', 'では、このしょるいにあたらしいじゅうしょをきにゅうして、ざいりゅうカードといっしょにだしてください。', 'Vậy anh/chị điền địa chỉ mới vào giấy này rồi nộp cùng thẻ cư trú nhé.'),
      turn('Người dân', '国民健康保険の手続きもここでできますか。', 'こくみんけんこうほけんのてつづきもここでできますか。', 'Thủ tục bảo hiểm y tế quốc dân cũng làm ở đây được không ạ?'),
      turn('Cán bộ', 'それは隣の２番窓口でお願いします。', 'それはとなりのにばんまどぐちでおねがいします。', 'Việc đó anh/chị làm ở quầy số 2 bên cạnh nhé.'),
    ],
    vocabularies: [
      word('市役所', 'しやくしょ', 'toà thị chính'),
      word('引っ越し', 'ひっこし', 'chuyển nhà'),
      word('手続き', 'てつづき', 'thủ tục'),
      word('転入届', 'てんにゅうとどけ', 'khai báo chuyển đến'),
      word('証明書', 'しょうめいしょ', 'giấy chứng nhận'),
      word('書類', 'しょるい', 'giấy tờ'),
      word('窓口', 'まどぐち', 'quầy giao dịch'),
      word('変更', 'へんこう', 'thay đổi'),
    ],
  },
  {
    title: 'Tình huống: Tìm thuê căn hộ',
    level: 'N3',
    order: 2,
    situation: 'real_estate',
    type: 'Tình huống',
    description: 'Nói điều kiện căn hộ, hỏi các khoản phí và hẹn đi xem phòng.',
    can_do_goals: [
      'Nói được điều kiện căn hộ mình cần',
      'Hỏi được các khoản phí khi thuê nhà',
      'Đề nghị được đi xem phòng',
    ],
    dialogue: [
      turn('Khách', '駅から歩いて１０分以内で、家賃が６万円以下の部屋を探しているんですが。', 'えきからあるいてじゅっぷんいないで、やちんがろくまんえんいかのへやをさがしているんですが。', 'Tôi đang tìm phòng cách ga dưới 10 phút đi bộ, tiền thuê từ 60.000 yên trở xuống.'),
      turn('Nhân viên', 'こちらはいかがでしょうか。駅から８分で、家賃は５万８千円です。', 'こちらはいかがでしょうか。えきからはっぷんで、やちんはごまんはっせんえんです。', 'Phòng này thì sao ạ? Cách ga 8 phút, tiền thuê 58.000 yên.'),
      turn('Khách', '敷金と礼金はかかりますか。', 'しききんとれいきんはかかりますか。', 'Có mất tiền đặt cọc và tiền lễ không ạ?'),
      turn('Nhân viên', '敷金は１か月分ですが、礼金はありません。', 'しききんはいっかげつぶんですが、れいきんはありません。', 'Tiền đặt cọc là một tháng tiền nhà, còn tiền lễ thì không có.'),
      turn('Khách', '外国人でも借りられますか。', 'がいこくじんでもかりられますか。', 'Người nước ngoài có thuê được không ạ?'),
      turn('Nhân viên', 'はい。ただ、保証会社との契約が必要になります。', 'はい。ただ、ほしょうがいしゃとのけいやくがひつようになります。', 'Được ạ. Nhưng cần ký hợp đồng với công ty bảo lãnh.'),
      turn('Khách', '一度、部屋を見せていただけますか。', 'いちど、へやをみせていただけますか。', 'Tôi có thể đến xem phòng một lần được không ạ?'),
    ],
    vocabularies: [
      word('家賃', 'やちん', 'tiền thuê nhà'),
      word('敷金', 'しききん', 'tiền đặt cọc'),
      word('礼金', 'れいきん', 'tiền lễ (trả cho chủ nhà)'),
      word('不動産屋', 'ふどうさんや', 'công ty môi giới nhà đất'),
      word('契約', 'けいやく', 'hợp đồng'),
      word('保証人', 'ほしょうにん', 'người bảo lãnh'),
      word('以内', 'いない', 'trong vòng'),
      word('探す', 'さがす', 'tìm kiếm'),
    ],
  },
  {
    title: 'Tình huống: Phỏng vấn xin việc làm thêm',
    level: 'N3',
    order: 3,
    situation: 'part_time_job',
    type: 'Tình huống',
    description: 'Trả lời phỏng vấn về lý do ứng tuyển, lịch làm và kinh nghiệm.',
    can_do_goals: [
      'Trình bày được lý do muốn làm công việc',
      'Nói được số ngày và khung giờ có thể đi làm',
      'Kể được kinh nghiệm làm việc trước đây',
    ],
    dialogue: [
      turn('Người phỏng vấn', '志望動機を教えてください。', 'しぼうどうきをおしえてください。', 'Bạn hãy cho biết lý do ứng tuyển.'),
      turn('Ứng viên', '接客の仕事を通して、日本語をもっと上達させたいと思ったからです。', 'せっきゃくのしごとをとおして、にほんごをもっとじょうたつさせたいとおもったからです。', 'Vì tôi muốn nâng cao tiếng Nhật hơn nữa thông qua công việc tiếp khách.'),
      turn('Người phỏng vấn', '週に何日ぐらい働けますか。', 'しゅうになんにちぐらいはたらけますか。', 'Một tuần bạn làm được khoảng mấy ngày?'),
      turn('Ứng viên', '学校があるので、週に３日、夕方から働けます。', 'がっこうがあるので、しゅうにみっか、ゆうがたからはたらけます。', 'Vì còn đi học nên tôi làm được 3 ngày một tuần, từ chiều tối.'),
      turn('Người phỏng vấn', '前にアルバイトの経験はありますか。', 'まえにアルバイトのけいけんはありますか。', 'Trước đây bạn đã có kinh nghiệm làm thêm chưa?'),
      turn('Ứng viên', 'はい、ベトナムのカフェで１年間働いていました。', 'はい、ベトナムのカフェでいちねんかんはたらいていました。', 'Có, tôi đã làm ở một quán cà phê tại Việt Nam trong một năm.'),
      turn('Người phỏng vấn', '分かりました。結果は来週メールで連絡します。', 'わかりました。けっかはらいしゅうメールでれんらくします。', 'Tôi hiểu rồi. Kết quả chúng tôi sẽ báo qua email vào tuần sau.'),
    ],
    vocabularies: [
      word('面接', 'めんせつ', 'phỏng vấn'),
      word('志望動機', 'しぼうどうき', 'lý do ứng tuyển'),
      word('接客', 'せっきゃく', 'tiếp khách'),
      word('経験', 'けいけん', 'kinh nghiệm'),
      word('応募', 'おうぼ', 'ứng tuyển'),
      word('結果', 'けっか', 'kết quả'),
      word('連絡', 'れんらく', 'liên lạc'),
      word('上達', 'じょうたつ', 'tiến bộ'),
    ],
  },
  {
    title: 'Tình huống: Kể bệnh sử khi đi khám',
    level: 'N3',
    order: 4,
    situation: 'hospital',
    type: 'Tình huống',
    description: 'Trả lời bác sĩ về bệnh đã từng mắc, thuốc đang dùng và dị ứng.',
    can_do_goals: [
      'Kể được bệnh đã từng mắc và phẫu thuật đã làm',
      'Nói được loại thuốc mình đang dùng',
      'Báo được với bác sĩ mình bị dị ứng gì',
    ],
    dialogue: [
      turn('Bác sĩ', '今までに大きな病気をしたことはありますか。', 'いままでにおおきなびょうきをしたことはありますか。', 'Từ trước đến nay anh/chị đã từng mắc bệnh gì nặng chưa?'),
      turn('Bệnh nhân', '５年前に胃の手術を受けました。', 'ごねんまえにいのしゅじゅつをうけました。', 'Năm năm trước tôi đã phẫu thuật dạ dày.'),
      turn('Bác sĩ', '今、飲んでいる薬はありますか。', 'いま、のんでいるくすりはありますか。', 'Hiện anh/chị có đang uống thuốc gì không?'),
      turn('Bệnh nhân', '血圧の薬を毎朝飲んでいます。', 'けつあつのくすりをまいあさのんでいます。', 'Tôi uống thuốc huyết áp mỗi sáng.'),
      turn('Bác sĩ', 'アレルギーはありますか。', 'アレルギーはありますか。', 'Anh/chị có bị dị ứng gì không?'),
      turn('Bệnh nhân', '卵を食べると、体がかゆくなります。', 'たまごをたべると、からだがかゆくなります。', 'Hễ ăn trứng là người tôi bị ngứa.'),
      turn('Bác sĩ', '分かりました。念のため、血液検査をしておきましょう。', 'わかりました。ねんのため、けつえきけんさをしておきましょう。', 'Tôi hiểu rồi. Để cho chắc, mình làm xét nghiệm máu luôn nhé.'),
    ],
    vocabularies: [
      word('手術', 'しゅじゅつ', 'phẫu thuật'),
      word('胃', 'い', 'dạ dày'),
      word('血圧', 'けつあつ', 'huyết áp'),
      word('アレルギー', 'アレルギー', 'dị ứng'),
      word('痒い', 'かゆい', 'ngứa'),
      word('念のため', 'ねんのため', 'để cho chắc'),
      word('血液', 'けつえき', 'máu'),
      word('症状', 'しょうじょう', 'triệu chứng'),
    ],
  },

  // ───────────────────────────── N2 ─────────────────────────────
  {
    title: 'Tình huống: Động đất và sơ tán',
    level: 'N2',
    order: 1,
    situation: 'emergency',
    type: 'Tình huống',
    description: 'Trao đổi với hàng xóm sau động đất: cảnh báo sóng thần và nơi sơ tán.',
    can_do_goals: [
      'Hiểu được thông báo cảnh báo thiên tai',
      'Xác nhận được địa điểm sơ tán được chỉ định',
      'Trao đổi được cách di chuyển an toàn khi sơ tán',
    ],
    dialogue: [
      turn('Hàng xóm A', '今の地震、揺れがすごかったですね。おけがはありませんでしたか。', 'いまのじしん、ゆれがすごかったですね。おけがはありませんでしたか。', 'Trận động đất vừa rồi rung dữ quá nhỉ. Anh có bị thương không?'),
      turn('Hàng xóm B', 'おかげさまで大丈夫でした。ただ、津波注意報が出ているそうです。', 'おかげさまでだいじょうぶでした。ただ、つなみちゅういほうがでているそうです。', 'May là tôi không sao. Nhưng nghe nói đang có cảnh báo sóng thần.'),
      turn('Hàng xóm A', '念のため、指定されている避難所に移動したほうがよさそうですね。', 'ねんのため、していされているひなんじょにいどうしたほうがよさそうですね。', 'Để cho chắc, có lẽ chúng ta nên di chuyển đến nơi sơ tán được chỉ định.'),
      turn('Hàng xóm B', 'この地区の避難所がどこか、ご存じですか。', 'このちくのひなんじょがどこか、ごぞんじですか。', 'Chị có biết nơi sơ tán của khu này ở đâu không?'),
      turn('Hàng xóm A', '近くの小学校です。貴重品と水だけ持って、すぐに向かいましょう。', 'ちかくのしょうがっこうです。きちょうひんとみずだけもって、すぐにむかいましょう。', 'Là trường tiểu học gần đây. Mình chỉ mang đồ quý giá và nước rồi đi ngay thôi.'),
      turn('Hàng xóm B', 'エレベーターは使わずに、階段で下りたほうがいいですね。', 'エレベーターはつかわずに、かいだんでおりたほうがいいですね。', 'Không nên dùng thang máy, đi thang bộ xuống thì hơn nhỉ.'),
    ],
    vocabularies: [
      word('地震', 'じしん', 'động đất'),
      word('揺れ', 'ゆれ', 'sự rung lắc'),
      word('津波', 'つなみ', 'sóng thần'),
      word('注意報', 'ちゅういほう', 'cảnh báo'),
      word('避難所', 'ひなんじょ', 'nơi sơ tán'),
      word('指定', 'してい', 'chỉ định'),
      word('貴重品', 'きちょうひん', 'đồ quý giá'),
      word('階段', 'かいだん', 'cầu thang'),
    ],
  },
  {
    title: 'Tình huống: Liên lạc công việc qua điện thoại',
    level: 'N2',
    order: 2,
    situation: 'phone_call',
    type: 'Tình huống',
    description: 'Gọi cho đối tác, nhờ chuyển lời khi người cần gặp vắng mặt.',
    can_do_goals: [
      'Tự giới thiệu đúng lối kính ngữ trong cuộc gọi công việc',
      'Nhờ được người nghe máy chuyển lời',
      'Xác nhận lại thông tin bằng cách đọc lại',
    ],
    dialogue: [
      turn('Nhân viên', 'お世話になっております。ABC商事の山田と申します。営業部の佐藤様はいらっしゃいますか。', 'おせわになっております。ABCしょうじのやまだともうします。えいぎょうぶのさとうさまはいらっしゃいますか。', 'Cảm ơn quý công ty đã luôn giúp đỡ. Tôi là Yamada của công ty thương mại ABC. Xin hỏi anh Sato phòng kinh doanh có ở đó không ạ?'),
      turn('Lễ tân', '申し訳ございません。佐藤はただいま席を外しております。', 'もうしわけございません。さとうはただいませきをはずしております。', 'Thành thật xin lỗi. Anh Sato hiện đang không có ở chỗ ạ.'),
      turn('Nhân viên', 'そうですか。では、お戻りになりましたら、お電話をいただけるようお伝え願えますか。', 'そうですか。では、おもどりになりましたら、おでんわをいただけるようおつたえねがえますか。', 'Vậy à. Vậy khi anh ấy quay lại, chị có thể nhắn giúp anh ấy gọi lại cho tôi được không ạ?'),
      turn('Lễ tân', 'かしこまりました。念のため、お電話番号を伺ってもよろしいでしょうか。', 'かしこまりました。ねんのため、おでんわばんごうをうかがってもよろしいでしょうか。', 'Vâng ạ. Để cho chắc, cho phép tôi hỏi số điện thoại của anh được không ạ?'),
      turn('Nhân viên', '０３の１２３４の５６７８です。', 'ゼロさんのいちにさんよんのごろくななはちです。', 'Là 03-1234-5678 ạ.'),
      turn('Lễ tân', '復唱いたします。０３の１２３４の５６７８、ABC商事の山田様ですね。確かに申し伝えます。', 'ふくしょういたします。ゼロさんのいちにさんよんのごろくななはち、ABCしょうじのやまださまですね。たしかにもうしつたえます。', 'Tôi xin đọc lại: 03-1234-5678, anh Yamada của công ty ABC. Tôi chắc chắn sẽ chuyển lời ạ.'),
    ],
    vocabularies: [
      word('商事', 'しょうじ', 'công ty thương mại'),
      word('営業部', 'えいぎょうぶ', 'phòng kinh doanh'),
      word('席を外す', 'せきをはずす', 'vắng mặt khỏi chỗ ngồi'),
      word('伝える', 'つたえる', 'truyền đạt, chuyển lời'),
      word('伺う', 'うかがう', 'hỏi, đến thăm (khiêm nhường)'),
      word('復唱', 'ふくしょう', 'đọc lại, nhắc lại'),
      word('申し伝える', 'もうしつたえる', 'chuyển lời (khiêm nhường)'),
      word('折り返し', 'おりかえし', 'gọi lại'),
    ],
  },
];

export default SITUATIONAL_LESSONS;
