/**
 * Bộ bài học theo chủ đề, tổ chức giống cách Tsunagaru (tsunagarujp.mext.go.jp)
 * trình bày: mỗi bài là một cảnh đời sống, có mục tiêu "làm được gì", một đoạn
 * hội thoại của cảnh đó và bảng từ vựng đi kèm. Cùng một chủ đề có thể có bài ở
 * nhiều cấp độ (ví dụ đi khám bệnh N4 chỉ nói triệu chứng, N3 kể bệnh sử).
 *
 * Phân bố: N5 12 bài · N4 19 · N3 4. Không có bài N2, N1: bài tình huống đi theo
 * video Tsunagaru, vốn chỉ có ba cấp tương đương N5–N3; người học N2, N1 luyện
 * đọc hiểu, ngữ pháp và đề JLPT ở các mục khác của app.
 *
 * N5 gồm đúng 12 bài theo thứ tự 12 chủ đề cấp 1 của Tsunagaru, N4 gồm đúng 19
 * bài theo 19 chủ đề cấp 2; bài nào cũng gắn video của chủ đề đó
 * (`data/lesson-videos/n5-*`, `n4-*`) — không có bài N5, N4 nào thiếu video,
 * để cả trình độ học theo cùng một kiểu. Từ vựng của bài N4 lấy từ bảng từ của
 * chính các cảnh video.
 *
 * Bài có video **không** có `dialogue` soạn sẵn: lời thoại của bài là kịch bản
 * chạy theo video. Hai đoạn hội thoại khác nhau cho cùng một tình huống chỉ
 * làm người học rối. `dialogue` ở đây dành cho bài chưa có video.
 *
 * ⚠️ Nội dung tiếng Nhật ở đây do Claude soạn và CHƯA được người biết tiếng Nhật
 * rà soát. Phải rà lại trước khi dùng trong bản bảo vệ hoặc demo chính thức.
 *
 * `title` là khoá tự nhiên để upsert: đổi tiêu đề một bài đã có sẽ tạo bài mới
 * và làm mất tiến độ học gắn với `_id` cũ.
 *
 * Dữ liệu thuần, không chạm DB — `seed-situational-lessons.js` lo phần ghi.
 */

const turn = (speaker, textJa, reading, textVi) => ({
  speaker,
  text_ja: textJa,
  reading,
  text_vi: textVi,
});

const word = (w, hiragana, meaning) => ({ word: w, hiragana, meaning });

export const SITUATIONAL_LESSONS = [
  // ───────────────────────────── N5 ─────────────────────────────
  {
    title: 'Tình huống: Tự giới thiệu',
    level: 'N5',
    order: 1,
    situation: 'self_introduction',
    type: 'Tình huống',
    description: 'Chào hỏi và giới thiệu bản thân khi gặp một người lần đầu.',
    can_do_goals: [
      'Chào hỏi lịch sự khi gặp ai đó lần đầu',
      'Nói được tên và đất nước của mình',
      'Hỏi được nghề nghiệp của người đối diện',
    ],
    vocabularies: [
      word('名前', 'なまえ', 'tên'),
      word('国', 'くに', 'đất nước'),
      word('仕事', 'しごと', 'công việc'),
      word('会社員', 'かいしゃいん', 'nhân viên công ty'),
      word('学生', 'がくせい', 'học sinh, sinh viên'),
      word('先生', 'せんせい', 'giáo viên'),
      word('友達', 'ともだち', 'bạn bè'),
      word('勉強', 'べんきょう', 'việc học'),
      word('私', 'わたし', 'tôi'),
      word('出身', 'しゅっしん', 'quê quán, xuất thân'),
      word('日本人', 'にほんじん', 'người Nhật'),
    ],
  },
  {
    title: 'Tình huống: Đi siêu thị',
    level: 'N5',
    order: 2,
    situation: 'supermarket',
    type: 'Tình huống',
    description: 'Hỏi giá, hỏi vị trí hàng hoá và thanh toán ở siêu thị.',
    can_do_goals: [
      'Hỏi được giá của một món hàng',
      'Hỏi được món hàng nằm ở đâu trong siêu thị',
      'Trả lời được khi nhân viên hỏi có cần túi không',
    ],
    vocabularies: [
      word('牛乳', 'ぎゅうにゅう', 'sữa tươi'),
      word('店員', 'てんいん', 'nhân viên cửa hàng'),
      word('棚', 'たな', 'kệ hàng'),
      word('袋', 'ふくろ', 'túi đựng'),
      word('値段', 'ねだん', 'giá cả'),
      word('会計', 'かいけい', 'thanh toán, tính tiền'),
      word('野菜', 'やさい', 'rau củ'),
      word('肉', 'にく', 'thịt'),
      word('卵', 'たまご', 'trứng'),
    ],
  },
  {
    title: 'Tình huống: Hỏi quầy hàng và giá',
    level: 'N5',
    order: 3,
    situation: 'shopping',
    type: 'Tình huống',
    description: 'Hỏi quầy hàng ở tầng nào, xác nhận giá và chọn món phù hợp trong cửa hàng lớn.',
    can_do_goals: [
      'Hỏi được quầy hàng mình cần nằm ở đâu',
      'Xác nhận được giá của một món hàng',
      'Hỏi được điểm khác nhau giữa hai món để chọn',
    ],
    vocabularies: [
      word('売り場', 'うりば', 'quầy hàng'),
      word('何階', 'なんがい', 'tầng mấy'),
      word('階段', 'かいだん', 'cầu thang'),
      word('エスカレーター', 'エスカレーター', 'thang cuốn'),
      word('タオル', 'タオル', 'khăn tắm'),
      word('安い', 'やすい', 'rẻ'),
      word('高い', 'たかい', 'đắt; cao'),
      word('違う', 'ちがう', 'khác nhau'),
      word('洗う', 'あらう', 'giặt, rửa'),
      word('乾く', 'かわく', 'khô'),
    ],
  },
  {
    title: 'Tình huống: Chọn đồ và đi thử',
    level: 'N5',
    order: 4,
    situation: 'shopping',
    type: 'Tình huống',
    description: 'Nói món mình đang tìm, xin đi thử và quyết định mua.',
    can_do_goals: [
      'Nói được mình đang tìm món đồ gì',
      'Xin phép thử trước khi mua',
      'Nói được cỡ của mình và quyết định mua',
    ],
    vocabularies: [
      word('靴', 'くつ', 'giày'),
      word('運動靴', 'うんどうぐつ', 'giày thể thao'),
      word('探す', 'さがす', 'tìm'),
      word('履く', 'はく', 'đi (giày), mặc (quần)'),
      word('軽い', 'かるい', 'nhẹ'),
      word('人気', 'にんき', 'được ưa chuộng'),
      word('試着', 'しちゃく', 'mặc thử'),
      word('鏡', 'かがみ', 'gương'),
      word('似合う', 'にあう', 'hợp, vừa với'),
    ],
  },
  {
    title: 'Tình huống: Nói mong muốn với nhân viên cửa hàng',
    level: 'N5',
    order: 5,
    situation: 'shopping',
    type: 'Tình huống',
    description: 'Xin xem màu khác, hỏi cỡ khác và nói khi đồ chưa vừa.',
    can_do_goals: [
      'Xin xem cùng món hàng nhưng màu khác',
      'Hỏi được có cỡ to hơn hoặc nhỏ hơn không',
      'Nói được đồ mặc thử chưa vừa ở chỗ nào',
    ],
    vocabularies: [
      word('服', 'ふく', 'quần áo'),
      word('色', 'いろ', 'màu sắc'),
      word('白', 'しろ', 'màu trắng'),
      word('黒', 'くろ', 'màu đen'),
      word('大きい', 'おおきい', 'to, lớn'),
      word('小さい', 'ちいさい', 'nhỏ'),
      word('長い', 'ながい', 'dài'),
      word('短い', 'みじかい', 'ngắn'),
      word('袖', 'そで', 'tay áo'),
      word('試着室', 'しちゃくしつ', 'phòng thử đồ'),
    ],
  },
  {
    title: 'Tình huống: Ở nhà hàng',
    level: 'N5',
    order: 6,
    situation: 'restaurant',
    type: 'Tình huống',
    description: 'Gọi món, hỏi món ăn và thanh toán ở nhà hàng.',
    can_do_goals: [
      'Gọi được món mình muốn ăn',
      'Hỏi được món nào ngon hoặc món nào không cay',
      'Xin được hoá đơn khi ăn xong',
    ],
    vocabularies: [
      word('注文', 'ちゅうもん', 'gọi món, đặt hàng'),
      word('料理', 'りょうり', 'món ăn'),
      word('飲み物', 'のみもの', 'đồ uống'),
      word('お茶', 'おちゃ', 'trà'),
      word('水', 'みず', 'nước'),
      word('辛い', 'からい', 'cay'),
      word('美味しい', 'おいしい', 'ngon'),
      word('店', 'みせ', 'quán, cửa hàng'),
      word('席', 'せき', 'chỗ ngồi'),
    ],
  },
  {
    title: 'Tình huống: Ở bưu điện',
    level: 'N5',
    order: 7,
    situation: 'post_office',
    type: 'Tình huống',
    description: 'Gửi bưu kiện về nước, chọn cách gửi và biết cách nhận lại hàng khi vắng nhà.',
    can_do_goals: [
      'Nói được mình muốn gửi đồ đi đâu',
      'Hỏi được giá và thời gian gửi',
      'Biết cách nhờ giao lại khi hàng đến lúc mình vắng nhà',
    ],
    vocabularies: [
      word('郵便局', 'ゆうびんきょく', 'bưu điện'),
      word('荷物', 'にもつ', 'hành lý, bưu kiện'),
      word('送る', 'おくる', 'gửi'),
      word('航空便', 'こうくうびん', 'gửi đường hàng không'),
      word('船便', 'ふなびん', 'gửi đường biển'),
      word('住所', 'じゅうしょ', 'địa chỉ'),
      word('切手', 'きって', 'tem thư'),
      word('手紙', 'てがみ', 'thư'),
      word('不在票', 'ふざいひょう', 'phiếu báo vắng nhà'),
      word('再配達', 'さいはいたつ', 'giao hàng lại'),
      word('頼む', 'たのむ', 'nhờ'),
    ],
  },
  {
    title: 'Tình huống: Đi tàu',
    level: 'N5',
    order: 8,
    situation: 'train',
    type: 'Tình huống',
    description: 'Mua vé, hỏi đường ra ga và hỏi tàu đi đúng tuyến.',
    can_do_goals: [
      'Hỏi được tàu nào đi đến nơi mình muốn',
      'Hỏi được giá vé và mua vé',
      'Hỏi được tàu khởi hành ở sân ga số mấy',
    ],
    vocabularies: [
      word('電車', 'でんしゃ', 'tàu điện'),
      word('駅', 'えき', 'nhà ga'),
      word('切符', 'きっぷ', 'vé'),
      word('改札', 'かいさつ', 'cửa soát vé'),
      word('乗り換え', 'のりかえ', 'chuyển tàu'),
      word('片道', 'かたみち', 'một chiều'),
      word('往復', 'おうふく', 'khứ hồi'),
      word('時刻表', 'じこくひょう', 'bảng giờ tàu'),
    ],
  },
  {
    title: 'Tình huống: Hỏi đường',
    level: 'N5',
    order: 9,
    situation: 'directions',
    type: 'Tình huống',
    description: 'Hỏi đường tới một địa điểm, hiểu chỉ dẫn rẽ trái, rẽ phải và đi thẳng.',
    can_do_goals: [
      'Hỏi được gần đây có địa điểm mình cần không',
      'Hiểu chỉ dẫn đi thẳng, rẽ trái, rẽ phải',
      'Hỏi được đi bộ mất bao lâu',
    ],
    vocabularies: [
      word('道', 'みち', 'con đường'),
      word('近く', 'ちかく', 'gần đây, chỗ gần'),
      word('信号', 'しんごう', 'đèn giao thông'),
      word('右', 'みぎ', 'bên phải'),
      word('左', 'ひだり', 'bên trái'),
      word('曲がる', 'まがる', 'rẽ'),
      word('隣', 'となり', 'bên cạnh'),
      word('歩く', 'あるく', 'đi bộ'),
      word('角', 'かど', 'góc đường'),
      word('遠い', 'とおい', 'xa'),
    ],
  },
  {
    title: 'Tình huống: Rút tiền và gửi tiết kiệm',
    level: 'N5',
    order: 10,
    situation: 'bank',
    type: 'Tình huống',
    description: 'Hỏi cách rút tiền ở máy ATM và nói mình muốn gửi tiết kiệm hằng tháng.',
    can_do_goals: [
      'Nói được mình muốn rút tiền',
      'Hỏi được rút tiền vào ngày nghỉ có mất phí không',
      'Nói được số tiền muốn tiết kiệm mỗi tháng',
    ],
    vocabularies: [
      word('お金', 'おかね', 'tiền'),
      word('引き出す', 'ひきだす', 'rút (tiền)'),
      word('預ける', 'あずける', 'gửi (tiền)'),
      word('貯金', 'ちょきん', 'tiền tiết kiệm; tiết kiệm'),
      word('手数料', 'てすうりょう', 'phí giao dịch'),
      word('毎月', 'まいつき', 'hằng tháng'),
      word('通帳', 'つうちょう', 'sổ tài khoản'),
      word('押す', 'おす', 'ấn, bấm'),
      word('暗証番号', 'あんしょうばんごう', 'mã PIN'),
    ],
  },
  {
    title: 'Tình huống: Quy tắc đổ rác',
    level: 'N5',
    order: 11,
    situation: 'neighborhood',
    type: 'Tình huống',
    description: 'Hỏi hàng xóm ngày đổ từng loại rác và cách vứt đồ cỡ lớn.',
    can_do_goals: [
      'Hỏi được loại rác nào đổ vào ngày nào',
      'Hỏi được phải đổ rác trước mấy giờ',
      'Biết cách hỏi khi muốn vứt đồ cỡ lớn',
    ],
    vocabularies: [
      word('ごみ', 'ごみ', 'rác'),
      word('燃えるごみ', 'もえるごみ', 'rác cháy được'),
      word('燃えないごみ', 'もえないごみ', 'rác không cháy được'),
      word('粗大ごみ', 'そだいごみ', 'rác cỡ lớn'),
      word('瓶', 'びん', 'chai lọ thuỷ tinh'),
      word('缶', 'かん', 'lon'),
      word('捨てる', 'すてる', 'vứt bỏ'),
      word('分ける', 'わける', 'phân loại, chia'),
      word('市役所', 'しやくしょ', 'ủy ban thành phố'),
      word('近所', 'きんじょ', 'hàng xóm, khu lân cận'),
    ],
  },
  {
    title: 'Tình huống: Dùng máy móc ở nơi làm việc',
    level: 'N5',
    order: 12,
    situation: 'workplace',
    type: 'Tình huống',
    description: 'Xin phép dùng máy photocopy, báo máy không chạy và làm theo hướng dẫn.',
    can_do_goals: [
      'Xin phép dùng máy móc ở nơi làm việc',
      'Báo được khi máy không chạy',
      'Xác nhận lại mình làm có đúng không',
    ],
    vocabularies: [
      word('コピー機', 'コピーき', 'máy photocopy'),
      word('使う', 'つかう', 'dùng, sử dụng'),
      word('動く', 'うごく', 'chạy, hoạt động'),
      word('壊れる', 'こわれる', 'bị hỏng'),
      word('紙', 'かみ', 'giấy'),
      word('入れる', 'いれる', 'cho vào'),
      word('ボタン', 'ボタン', 'nút bấm'),
      word('電源', 'でんげん', 'nguồn điện'),
      word('先輩', 'せんぱい', 'đàn anh, đàn chị'),
    ],
  },

  // ───────────────────────────── N4 ─────────────────────────────
  {
    title: 'Tình huống: Chào hỏi đúng người, đúng lúc',
    level: 'N4',
    order: 1,
    situation: 'daily_life',
    type: 'Tình huống',
    description: 'Chào hỏi, cúi chào và nói lời chúc mừng, thăm hỏi, chia buồn đúng người, đúng lúc.',
    can_do_goals: [
      'Chọn được lời chào hợp với người và thời điểm',
      'Nói được lời chúc mừng, thăm hỏi và chia buồn',
      'Hỏi được cách mừng cưới ở Nhật',
    ],
    vocabularies: [
      word('挨拶', 'あいさつ', 'lời chào'),
      word('おめでとうございます', 'おめでとうございます', 'chúc mừng'),
      word('結婚式', 'けっこんしき', 'đám cưới'),
      word('お辞儀', 'おじぎ', 'cúi chào'),
      word('葬式', 'そうしき', 'đám tang'),
      word('招待状', 'しょうたいじょう', 'thiệp mời'),
      word('会釈', 'えしゃく', 'gật đầu chào'),
      word('ご愁傷様です', 'ごしゅうしょうさまです', 'xin chia buồn'),
      word('同期', 'どうき', 'người vào công ty cùng đợt'),
      word('職場', 'しょくば', 'nơi làm việc'),
      word('見舞い', 'みまい', 'việc đi thăm người ốm'),
      word('のし袋', 'のしぶくろ', 'phong bì mừng'),
    ],
  },
  {
    title: 'Tình huống: Dùng dịch vụ ở cửa hàng tiện lợi',
    level: 'N4',
    order: 2,
    situation: 'convenience_store',
    type: 'Tình huống',
    description: 'Mua cơm hộp, trả hóa đơn và rút tiền ở cửa hàng tiện lợi.',
    can_do_goals: [
      'Biết cửa hàng tiện lợi làm được những dịch vụ gì',
      'Trả hóa đơn và rút tiền ATM ở cửa hàng tiện lợi',
      'Trả lời được các câu hỏi của nhân viên thu ngân',
    ],
    vocabularies: [
      word('デパート', 'デパート', 'cửa hàng bách hóa'),
      word('電気料金', 'でんきりょうきん', 'tiền điện'),
      word('弁当', 'べんとう', 'cơm hộp'),
      word('贈り物', 'おくりもの', 'quà tặng'),
      word('払う', 'はらう', 'trả tiền'),
      word('温める', 'あたためる', 'hâm nóng'),
      word('日用品', 'にちようひん', 'đồ dùng hằng ngày'),
      word('お金を下ろす', 'おかねをおろす', 'rút tiền'),
      word('箸', 'はし', 'đũa'),
      word('冷凍食品', 'れいとうしょくひん', 'thực phẩm đông lạnh'),
      word('手数料', 'てすうりょう', 'phí giao dịch'),
      word('スプーン', 'スプーン', 'thìa'),
    ],
  },
  {
    title: 'Tình huống: Chọn cửa hàng phù hợp',
    level: 'N4',
    order: 3,
    situation: 'restaurant',
    type: 'Tình huống',
    description: 'Hỏi chỗ chụp ảnh thẻ, gọi món trưa và gọi điện đặt bàn ở nhà hàng.',
    can_do_goals: [
      'Đặt bàn nhà hàng qua điện thoại',
      'Gọi món và hỏi món nào ra nhanh nhất',
      'Nói lý do mong muốn của mình bằng「〜ので」',
    ],
    vocabularies: [
      word('予約', 'よやく', 'đặt chỗ'),
      word('本日', 'ほんじつ', 'hôm nay (lịch sự)'),
      word('証明写真', 'しょうめいしゃしん', 'ảnh thẻ'),
      word('何名様', 'なんめいさま', 'mấy vị khách'),
      word('おすすめ', 'おすすめ', 'được giới thiệu'),
      word('必要', 'ひつよう', 'cần thiết'),
      word('連絡先', 'れんらくさき', 'thông tin liên lạc'),
      word('ランチ', 'ランチ', 'bữa trưa'),
      word('撮る', 'とる', 'chụp (ảnh)'),
      word('電話番号', 'でんわばんごう', 'số điện thoại'),
      word('ドリンクバー', 'ドリンクバー', 'quầy nước tự chọn'),
      word('駅前', 'えきまえ', 'trước nhà ga'),
    ],
  },
  {
    title: 'Tình huống: Tiệm tóc, tiệm giặt và cửa hàng điện thoại',
    level: 'N4',
    order: 4,
    situation: 'shopping',
    type: 'Tình huống',
    description: 'Nhờ giặt áo gấp, cắt tóc theo ý mình và mua điện thoại, chọn gói cước.',
    can_do_goals: [
      'Nhờ giặt gấp ở tiệm giặt là',
      'Nói được kiểu tóc mình muốn ở tiệm làm tóc',
      'Chọn được máy và gói cước điện thoại',
    ],
    vocabularies: [
      word('会員証', 'かいいんしょう', 'thẻ hội viên'),
      word('カット', 'カット', 'cắt tóc'),
      word('機種変更', 'きしゅへんこう', 'đổi máy'),
      word('記入', 'きにゅう', 'điền vào'),
      word('シャンプー', 'シャンプー', 'gội đầu'),
      word('新規', 'しんき', 'đăng ký mới'),
      word('急ぎ', 'いそぎ', 'gấp'),
      word('短い', 'みじかい', 'ngắn'),
      word('機種', 'きしゅ', 'mẫu máy'),
      word('今日中', 'きょうじゅう', 'trong hôm nay'),
      word('切る', 'きる', 'cắt'),
      word('料金プラン', 'りょうきんプラン', 'gói cước'),
    ],
  },
  {
    title: 'Tình huống: Mua sắm khéo ở siêu thị',
    level: 'N4',
    order: 5,
    situation: 'supermarket',
    type: 'Tình huống',
    description: 'Đọc nhãn thành phần, xem tờ quảng cáo và hỏi lại khi giá tính tiền không đúng.',
    can_do_goals: [
      'Hỏi được thực phẩm có chất gây dị ứng không',
      'Đọc tờ quảng cáo và chọn món giá tốt',
      'Nói được với nhân viên khi giá không đúng',
    ],
    vocabularies: [
      word('大豆', 'だいず', 'đậu nành'),
      word('バーベキュー', 'バーベキュー', 'tiệc nướng'),
      word('値段', 'ねだん', 'giá'),
      word('アレルギー', 'アレルギー', 'dị ứng'),
      word('新聞', 'しんぶん', 'báo'),
      word('違う', 'ちがう', 'khác, sai'),
      word('食パン', 'しょくパン', 'bánh mì gối'),
      word('チラシ', 'チラシ', 'tờ quảng cáo'),
      word('割引', 'わりびき', 'giảm giá'),
      word('原材料名', 'げんざいりょうめい', 'tên nguyên liệu'),
      word('国産', 'こくさん', 'hàng trong nước'),
      word('さっき', 'さっき', 'lúc nãy'),
    ],
  },
  {
    title: 'Tình huống: Tham gia tổ dân phố',
    level: 'N4',
    order: 6,
    situation: 'neighborhood',
    type: 'Tình huống',
    description: 'Hỏi về tổ dân phố, xin vào tổ và chuẩn bị cho lượt dọn chỗ đổ rác.',
    can_do_goals: [
      'Hỏi được nghĩa của từ lạ bằng「〜って何ですか」',
      'Xin vào tổ dân phố và hiểu các hoạt động',
      'Nhờ hàng xóm chỉ cách làm lượt trực dọn rác',
    ],
    vocabularies: [
      word('町内会', 'ちょうないかい', 'tổ dân phố'),
      word('会費', 'かいひ', 'hội phí'),
      word('ごみ置き場', 'ごみおきば', 'chỗ đổ rác'),
      word('回覧板', 'かいらんばん', 'bảng thông báo truyền tay'),
      word('花見', 'はなみ', 'ngắm hoa anh đào'),
      word('掃除', 'そうじ', 'dọn dẹp'),
      word('地域', 'ちいき', 'khu vực'),
      word('防災訓練', 'ぼうさいくんれん', 'diễn tập phòng chống thiên tai'),
      word('格好', 'かっこう', 'trang phục'),
      word('活動', 'かつどう', 'hoạt động'),
      word('当番', 'とうばん', 'phiên trực'),
      word('軍手', 'ぐんて', 'găng tay vải'),
    ],
  },
  {
    title: 'Tình huống: Đi sự kiện và tìm sở thích mới',
    level: 'N4',
    order: 7,
    situation: 'events',
    type: 'Tình huống',
    description: 'Rủ nhau đi chợ đồ cũ, lễ hội mùa hè và tìm một việc mới cho ngày nghỉ.',
    can_do_goals: [
      'Hỏi được sự kiện có cần đăng ký không',
      'Nói được kinh nghiệm bằng「〜たことがあります」',
      'Nhờ người khác gợi ý việc làm vào ngày nghỉ',
    ],
    vocabularies: [
      word('フリーマーケット', 'フリーマーケット', 'chợ đồ cũ'),
      word('生活', 'せいかつ', 'cuộc sống'),
      word('夏祭り', 'なつまつり', 'lễ hội mùa hè'),
      word('売る', 'うる', 'bán'),
      word('暇', 'ひま', 'rảnh rỗi'),
      word('お好み焼き', 'おこのみやき', 'bánh xèo Nhật'),
      word('申し込み', 'もうしこみ', 'đăng ký'),
      word('図書館', 'としょかん', 'thư viện'),
      word('金魚すくい', 'きんぎょすくい', 'vớt cá vàng'),
      word('子ども会', 'こどもかい', 'hội phụ huynh trẻ em'),
      word('外国語', 'がいこくご', 'tiếng nước ngoài'),
      word('楽しみ', 'たのしみ', 'mong chờ'),
    ],
  },
  {
    title: 'Tình huống: Đi khám bệnh',
    level: 'N4',
    order: 8,
    situation: 'hospital',
    type: 'Tình huống',
    description: 'Lần đầu đến phòng khám, nói triệu chứng với bác sĩ và nhận đơn thuốc.',
    can_do_goals: [
      'Nói được triệu chứng và điền phiếu khai bệnh',
      'Kể nguyên nhân bị thương và xin phép bác sĩ',
      'Hiểu thẻ khám bệnh và đơn thuốc',
    ],
    vocabularies: [
      word('初診', 'しょしん', 'khám lần đầu'),
      word('診察室', 'しんさつしつ', 'phòng khám'),
      word('診察券', 'しんさつけん', 'thẻ khám bệnh'),
      word('保険証', 'ほけんしょう', 'thẻ bảo hiểm'),
      word('足首', 'あしくび', 'cổ chân'),
      word('処方箋', 'しょほうせん', 'đơn thuốc'),
      word('問診票', 'もんしんひょう', 'phiếu khai bệnh'),
      word('腫れる', 'はれる', 'sưng'),
      word('薬局', 'やっきょく', 'hiệu thuốc'),
      word('熱を測る', 'ねつをはかる', 'đo nhiệt độ'),
      word('転ぶ', 'ころぶ', 'ngã'),
      word('次回', 'じかい', 'lần sau'),
    ],
  },
  {
    title: 'Tình huống: Nhờ giúp đỡ khi khẩn cấp',
    level: 'N4',
    order: 9,
    situation: 'emergency',
    type: 'Tình huống',
    description: 'Nhờ người đi đường giúp, gọi cảnh sát 110 và gọi xe cấp cứu 119.',
    can_do_goals: [
      'Nhờ người lạ giúp khi có tai nạn',
      'Gọi được cảnh sát 110 và nói địa điểm',
      'Gọi được 119 xin xe cấp cứu',
    ],
    vocabularies: [
      word('警察', 'けいさつ', 'cảnh sát'),
      word('助ける', 'たすける', 'giúp'),
      word('火事', 'かじ', 'hỏa hoạn'),
      word('事件', 'じけん', 'vụ án'),
      word('外国人', 'がいこくじん', 'người nước ngoài'),
      word('救急', 'きゅうきゅう', 'cấp cứu'),
      word('事故', 'じこ', 'tai nạn'),
      word('呼ぶ', 'よぶ', 'gọi'),
      word('消防', 'しょうぼう', 'cứu hỏa'),
      word('はねる', 'はねる', 'đâm (xe)'),
      word('待つ', 'まつ', 'đợi'),
      word('階段', 'かいだん', 'cầu thang'),
    ],
  },
  {
    title: 'Tình huống: Thuế, bảo hiểm và đăng ký cư trú',
    level: 'N4',
    order: 10,
    situation: 'city_hall',
    type: 'Tình huống',
    description: 'Đăng ký cư trú ở tòa thị chính và hỏi về thuế, bảo hiểm, lương hưu.',
    can_do_goals: [
      'Làm được thủ tục đăng ký cư trú',
      'Hỏi được về các khoản trừ trong phiếu lương',
      'Hiểu bảo hiểm y tế và lương hưu',
    ],
    vocabularies: [
      word('手続き', 'てつづき', 'thủ tục'),
      word('給料', 'きゅうりょう', 'tiền lương'),
      word('保険', 'ほけん', 'bảo hiểm'),
      word('住民登録', 'じゅうみんとうろく', 'đăng ký cư trú'),
      word('給与明細', 'きゅうよめいさい', 'phiếu lương'),
      word('健康保険', 'けんこうほけん', 'bảo hiểm y tế'),
      word('住民', 'じゅうみん', 'cư dân'),
      word('所得税', 'しょとくぜい', 'thuế thu nhập'),
      word('年金', 'ねんきん', 'lương hưu'),
      word('パスポート', 'パスポート', 'hộ chiếu'),
      word('住民税', 'じゅうみんぜい', 'thuế cư trú'),
      word('制度', 'せいど', 'chế độ'),
    ],
  },
  {
    title: 'Tình huống: Ở thư viện',
    level: 'N4',
    order: 11,
    situation: 'library',
    type: 'Tình huống',
    description: 'Làm thẻ thư viện lần đầu, hỏi số sách được mượn và hạn trả sách.',
    can_do_goals: [
      'Điền được đơn làm thẻ thư viện',
      'Hỏi được được mượn bao nhiêu cuốn và sách ở đâu',
      'Hỏi được hạn trả và cách trả sách',
    ],
    vocabularies: [
      word('市内', 'しない', 'trong thành phố'),
      word('貸し出しカード', 'かしだしカード', 'thẻ mượn sách'),
      word('辞書', 'じしょ', 'từ điển'),
      word('西暦', 'せいれき', 'năm dương lịch'),
      word('利用案内', 'りようあんない', 'hướng dẫn sử dụng'),
      word('館内', 'かんない', 'trong thư viện'),
      word('携帯電話', 'けいたいでんわ', 'điện thoại di động'),
      word('借りる', 'かりる', 'mượn'),
      word('返却', 'へんきゃく', 'trả lại'),
      word('住所', 'じゅうしょ', 'địa chỉ'),
      word('英語', 'えいご', 'tiếng Anh'),
      word('返す', 'かえす', 'trả'),
    ],
  },
  {
    title: 'Tình huống: Gửi thư và thiệp năm mới',
    level: 'N4',
    order: 12,
    situation: 'post_office',
    type: 'Tình huống',
    description: 'Gửi thư chuyển phát nhanh, viết lời chúc và địa chỉ trên thiệp năm mới.',
    can_do_goals: [
      'Nhờ gửi thư chuyển phát nhanh cho kịp hạn',
      'Viết được lời chúc trên thiệp năm mới',
      'Viết được địa chỉ và tên người nhận kèm「様」',
    ],
    vocabularies: [
      word('送る', 'おくる', 'gửi'),
      word('年賀状', 'ねんがじょう', 'thiệp năm mới'),
      word('郵便番号', 'ゆうびんばんごう', 'mã bưu điện'),
      word('届ける', 'とどける', 'gửi đến'),
      word('書き方', 'かきかた', 'cách viết'),
      word('住所', 'じゅうしょ', 'địa chỉ'),
      word('速達', 'そくたつ', 'chuyển phát nhanh'),
      word('あけましておめでとうございます', 'あけましておめでとうございます', 'chúc mừng năm mới'),
      word('二行', 'にぎょう', 'hai dòng'),
      word('間に合う', 'まにあう', 'kịp'),
      word('元旦', 'がんたん', 'mùng 1 Tết'),
      word('出す', 'だす', 'gửi (thư)'),
    ],
  },
  {
    title: 'Tình huống: Dùng máy tính và điện thoại',
    level: 'N4',
    order: 13,
    situation: 'workplace',
    type: 'Tình huống',
    description: 'Gõ chữ Nhật trên máy tính, nhờ xem email và gọi trung tâm đồ thất lạc.',
    can_do_goals: [
      'Nói được khi máy tính không gõ được chữ Nhật',
      'Nhờ đồng nghiệp xem email và hỏi BCC, CC',
      'Gọi được trung tâm đồ thất lạc',
    ],
    vocabularies: [
      word('調べる', 'しらべる', 'tra cứu'),
      word('ミーティング', 'ミーティング', 'cuộc họp'),
      word('忘れ物', 'わすれもの', 'đồ bỏ quên'),
      word('入力', 'にゅうりょく', 'nhập (chữ)'),
      word('お知らせ', 'おしらせ', 'thông báo'),
      word('定期券', 'ていきけん', 'vé tháng'),
      word('キー', 'キー', 'phím'),
      word('メール', 'メール', 'email'),
      word('落とす', 'おとす', 'đánh rơi'),
      word('ローマ字', 'ローマじ', 'chữ La-tinh'),
      word('受信', 'じゅしん', 'nhận (thư)'),
      word('利用区間', 'りようくかん', 'chặng sử dụng'),
    ],
  },
  {
    title: 'Tình huống: An toàn khi làm việc',
    level: 'N4',
    order: 14,
    situation: 'workplace',
    type: 'Tình huống',
    description: 'Chỉ tay hô to xác nhận an toàn, nghe nhắc nhở buổi sáng và họp dự đoán nguy hiểm.',
    can_do_goals: [
      'Làm được động tác chỉ tay hô to xác nhận an toàn',
      'Nhờ dịch tài liệu an toàn sang tiếng nước mình',
      'Nói được điều nguy hiểm và hỏi nghĩa từ khó',
    ],
    vocabularies: [
      word('指差呼称', 'しさこしょう', 'chỉ tay hô to'),
      word('スプレー缶', 'スプレーかん', 'bình xịt'),
      word('定例', 'ていれい', 'định kỳ'),
      word('安全', 'あんぜん', 'an toàn'),
      word('換気', 'かんき', 'thông gió'),
      word('危険予知', 'きけんよち', 'dự đoán nguy hiểm'),
      word('確認', 'かくにん', 'xác nhận'),
      word('火気厳禁', 'かきげんきん', 'cấm lửa'),
      word('一酸化炭素', 'いっさんかたんそ', 'khí CO'),
      word('前方', 'ぜんぽう', 'phía trước'),
      word('復唱', 'ふくしょう', 'đọc lại theo'),
      word('中毒', 'ちゅうどく', 'ngộ độc'),
    ],
  },
  {
    title: 'Tình huống: Xử lý tai nạn ở nơi làm việc',
    level: 'N4',
    order: 15,
    situation: 'workplace',
    type: 'Tình huống',
    description: 'Gọi người giúp khi có người ngã, báo cáo sự việc và làm thủ tục bảo hiểm tai nạn lao động.',
    can_do_goals: [
      'Gọi người giúp khi có tai nạn',
      'Báo cáo được sự việc với quản lý',
      'Hỏi được thủ tục bảo hiểm tai nạn lao động',
    ],
    vocabularies: [
      word('痛い', 'いたい', 'đau'),
      word('報告', 'ほうこく', 'báo cáo'),
      word('歩道橋', 'ほどうきょう', 'cầu vượt bộ hành'),
      word('看護師', 'かんごし', 'y tá'),
      word('現場', 'げんば', 'hiện trường'),
      word('踏み外す', 'ふみはずす', 'trượt chân'),
      word('動く', 'うごく', 'cử động'),
      word('対応', 'たいおう', 'xử lý'),
      word('捻挫', 'ねんざ', 'bong gân'),
      word('呼ぶ', 'よぶ', 'gọi'),
      word('自動ドア', 'じどうドア', 'cửa tự động'),
      word('労災', 'ろうさい', 'tai nạn lao động'),
    ],
  },
  {
    title: 'Tình huống: Tìm việc làm',
    level: 'N4',
    order: 16,
    situation: 'job_hunting',
    type: 'Tình huống',
    description: 'Xem tờ tuyển dụng, đăng ký tìm việc ở Hello Work và nghe giới thiệu công việc.',
    can_do_goals: [
      'Hỏi được gần đây có công việc nào tốt không',
      'Đăng ký tìm việc ở Hello Work',
      'Hỏi lại từ khó trong thông tin tuyển dụng',
    ],
    vocabularies: [
      word('募集', 'ぼしゅう', 'tuyển dụng'),
      word('紹介', 'しょうかい', 'giới thiệu'),
      word('工場', 'こうじょう', 'nhà máy'),
      word('時給', 'じきゅう', 'lương theo giờ'),
      word('窓口', 'まどぐち', 'quầy giao dịch'),
      word('仕分け', 'しわけ', 'phân loại'),
      word('レジ', 'レジ', 'quầy thu ngân'),
      word('求職', 'きゅうしょく', 'tìm việc'),
      word('ラベル', 'ラベル', 'nhãn'),
      word('清掃', 'せいそう', 'dọn vệ sinh'),
      word('手続き', 'てつづき', 'thủ tục'),
      word('交通費', 'こうつうひ', 'phí đi lại'),
    ],
  },
  {
    title: 'Tình huống: Phỏng vấn và ký hợp đồng',
    level: 'N4',
    order: 17,
    situation: 'job_hunting',
    type: 'Tình huống',
    description: 'Nói nguyện vọng việc làm, trả lời phỏng vấn và hỏi lại khi ký hợp đồng lao động.',
    can_do_goals: [
      'Nói được mình muốn làm nhân viên chính thức',
      'Trả lời được câu hỏi phỏng vấn và hỏi lại từ khó',
      'Hỏi lại được các điều khoản khi ký hợp đồng',
    ],
    vocabularies: [
      word('在留資格', 'ざいりゅうしかく', 'tư cách lưu trú'),
      word('面接', 'めんせつ', 'phỏng vấn'),
      word('契約書', 'けいやくしょ', 'hợp đồng'),
      word('定住者', 'ていじゅうしゃ', 'người định trú'),
      word('履歴書', 'りれきしょ', 'sơ yếu lý lịch'),
      word('週休', 'しゅうきゅう', 'ngày nghỉ trong tuần'),
      word('経験', 'けいけん', 'kinh nghiệm'),
      word('経歴', 'けいれき', 'quá trình làm việc'),
      word('シフト', 'シフト', 'ca làm'),
      word('正社員', 'せいしゃいん', 'nhân viên chính thức'),
      word('教師', 'きょうし', 'giáo viên'),
      word('試用期間', 'しようきかん', 'thời gian thử việc'),
    ],
  },
  {
    title: 'Tình huống: Giao tiếp với đồng nghiệp',
    level: 'N4',
    order: 18,
    situation: 'workplace',
    type: 'Tình huống',
    description: 'Nghe điện thoại khi đồng nghiệp vắng, rủ đi ăn và từ chối khéo, nói chuyện về lời chào ở công ty.',
    can_do_goals: [
      'Nhận điện thoại và ghi lời nhắn cho đồng nghiệp',
      'Rủ và từ chối lời rủ một cách nhẹ nhàng',
      'Hiểu khi nào dùng「お疲れさまです」',
    ],
    vocabularies: [
      word('資材課', 'しざいか', 'phòng vật tư'),
      word('うどん屋', 'うどんや', 'quán udon'),
      word('便利', 'べんり', 'tiện lợi'),
      word('総務課', 'そうむか', 'phòng tổng vụ'),
      word('工事中', 'こうじちゅう', 'đang thi công'),
      word('入社', 'にゅうしゃ', 'vào công ty'),
      word('席を外す', 'せきをはずす', 'vắng khỏi chỗ'),
      word('集計', 'しゅうけい', 'tổng hợp số liệu'),
      word('取引先', 'とりひきさき', 'đối tác'),
      word('会議中', 'かいぎちゅう', 'đang họp'),
      word('食欲', 'しょくよく', 'cảm giác thèm ăn'),
      word('社長', 'しゃちょう', 'giám đốc'),
    ],
  },
  {
    title: 'Tình huống: Xin nghỉ phép và về sớm',
    level: 'N4',
    order: 19,
    situation: 'workplace',
    type: 'Tình huống',
    description: 'Xin nghỉ phép có lương, cảm ơn đồng nghiệp sau kỳ nghỉ và xin về sớm khi con bị sốt.',
    can_do_goals: [
      'Xin phép cấp trên về sớm một cách lịch sự',
      'Xin nghỉ phép có lương, nói rõ lý do và số ngày',
      'Cảm ơn đồng nghiệp đã giúp lúc mình nghỉ',
    ],
    vocabularies: [
      word('保育園', 'ほいくえん', 'nhà trẻ'),
      word('両親', 'りょうしん', 'bố mẹ'),
      word('おかげさまで', 'おかげさまで', 'nhờ anh chị (mà…)'),
      word('熱を出す', 'ねつをだす', 'bị sốt'),
      word('有給', 'ゆうきゅう', 'nghỉ phép có lương'),
      word('久しぶり', 'ひさしぶり', 'lâu lắm rồi'),
      word('迎える', 'むかえる', 'đón'),
      word('残る', 'のこる', 'còn lại'),
      word('配る', 'くばる', 'phát, chia'),
      word('早退', 'そうたい', 'về sớm'),
      word('調整', 'ちょうせい', 'điều chỉnh'),
      word('外出', 'がいしゅつ', 'ra ngoài'),
    ],
  },

  // ───────────────────────────── N3 ─────────────────────────────
  {
    title: 'Tình huống: Làm thủ tục chuyển nơi ở',
    level: 'N3',
    order: 1,
    situation: 'city_hall',
    type: 'Tình huống',
    description: 'Khai báo chuyển đến ở toà thị chính và hỏi quầy làm thủ tục bảo hiểm.',
    can_do_goals: [
      'Trình bày được mục đích làm thủ tục',
      'Chuẩn bị đúng giấy tờ khi chuyển nơi ở',
      'Hỏi được quầy xử lý một thủ tục khác',
    ],
    dialogue: [
      turn('Người dân', 'すみません、引っ越してきたので、住所変更の手続きをしたいのですが。', 'すみません、ひっこしてきたので、じゅうしょへんこうのてつづきをしたいのですが。', 'Xin lỗi, tôi mới chuyển nhà đến nên muốn làm thủ tục đổi địa chỉ ạ.'),
      turn('Cán bộ', '転入届ですね。前の市役所でもらった転出証明書はお持ちですか。', 'てんにゅうとどけですね。まえのしやくしょでもらったてんしゅつしょうめいしょはおもちですか。', 'Là khai báo chuyển đến nhỉ. Anh/chị có mang giấy chứng nhận chuyển đi lấy ở toà thị chính cũ không?'),
      turn('Người dân', 'はい、持ってきました。', 'はい、もってきました。', 'Có, tôi có mang theo.'),
      turn('Cán bộ', 'では、この書類に新しい住所を記入して、在留カードと一緒に出してください。', 'では、このしょるいにあたらしいじゅうしょをきにゅうして、ざいりゅうカードといっしょにだしてください。', 'Vậy anh/chị điền địa chỉ mới vào giấy này rồi nộp cùng thẻ cư trú nhé.'),
      turn('Người dân', '国民健康保険の手続きもここでできますか。', 'こくみんけんこうほけんのてつづきもここでできますか。', 'Thủ tục bảo hiểm y tế quốc dân cũng làm ở đây được không ạ?'),
      turn('Cán bộ', 'それは隣の２番窓口でお願いします。', 'それはとなりのにばんまどぐちでおねがいします。', 'Việc đó anh/chị làm ở quầy số 2 bên cạnh nhé.'),
    ],
    vocabularies: [
      word('市役所', 'しやくしょ', 'toà thị chính'),
      word('引っ越し', 'ひっこし', 'chuyển nhà'),
      word('手続き', 'てつづき', 'thủ tục'),
      word('転入届', 'てんにゅうとどけ', 'khai báo chuyển đến'),
      word('証明書', 'しょうめいしょ', 'giấy chứng nhận'),
      word('書類', 'しょるい', 'giấy tờ'),
      word('窓口', 'まどぐち', 'quầy giao dịch'),
      word('変更', 'へんこう', 'thay đổi'),
    ],
  },
  {
    title: 'Tình huống: Tìm thuê căn hộ',
    level: 'N3',
    order: 2,
    situation: 'real_estate',
    type: 'Tình huống',
    description: 'Nói điều kiện căn hộ, hỏi các khoản phí và hẹn đi xem phòng.',
    can_do_goals: [
      'Nói được điều kiện căn hộ mình cần',
      'Hỏi được các khoản phí khi thuê nhà',
      'Đề nghị được đi xem phòng',
    ],
    dialogue: [
      turn('Khách', '駅から歩いて１０分以内で、家賃が６万円以下の部屋を探しているんですが。', 'えきからあるいてじゅっぷんいないで、やちんがろくまんえんいかのへやをさがしているんですが。', 'Tôi đang tìm phòng cách ga dưới 10 phút đi bộ, tiền thuê từ 60.000 yên trở xuống.'),
      turn('Nhân viên', 'こちらはいかがでしょうか。駅から８分で、家賃は５万８千円です。', 'こちらはいかがでしょうか。えきからはっぷんで、やちんはごまんはっせんえんです。', 'Phòng này thì sao ạ? Cách ga 8 phút, tiền thuê 58.000 yên.'),
      turn('Khách', '敷金と礼金はかかりますか。', 'しききんとれいきんはかかりますか。', 'Có mất tiền đặt cọc và tiền lễ không ạ?'),
      turn('Nhân viên', '敷金は１か月分ですが、礼金はありません。', 'しききんはいっかげつぶんですが、れいきんはありません。', 'Tiền đặt cọc là một tháng tiền nhà, còn tiền lễ thì không có.'),
      turn('Khách', '外国人でも借りられますか。', 'がいこくじんでもかりられますか。', 'Người nước ngoài có thuê được không ạ?'),
      turn('Nhân viên', 'はい。ただ、保証会社との契約が必要になります。', 'はい。ただ、ほしょうがいしゃとのけいやくがひつようになります。', 'Được ạ. Nhưng cần ký hợp đồng với công ty bảo lãnh.'),
      turn('Khách', '一度、部屋を見せていただけますか。', 'いちど、へやをみせていただけますか。', 'Tôi có thể đến xem phòng một lần được không ạ?'),
    ],
    vocabularies: [
      word('家賃', 'やちん', 'tiền thuê nhà'),
      word('敷金', 'しききん', 'tiền đặt cọc'),
      word('礼金', 'れいきん', 'tiền lễ (trả cho chủ nhà)'),
      word('不動産屋', 'ふどうさんや', 'công ty môi giới nhà đất'),
      word('契約', 'けいやく', 'hợp đồng'),
      word('保証人', 'ほしょうにん', 'người bảo lãnh'),
      word('以内', 'いない', 'trong vòng'),
      word('探す', 'さがす', 'tìm kiếm'),
    ],
  },
  {
    title: 'Tình huống: Phỏng vấn xin việc làm thêm',
    level: 'N3',
    order: 3,
    situation: 'part_time_job',
    type: 'Tình huống',
    description: 'Trả lời phỏng vấn về lý do ứng tuyển, lịch làm và kinh nghiệm.',
    can_do_goals: [
      'Trình bày được lý do muốn làm công việc',
      'Nói được số ngày và khung giờ có thể đi làm',
      'Kể được kinh nghiệm làm việc trước đây',
    ],
    dialogue: [
      turn('Người phỏng vấn', '志望動機を教えてください。', 'しぼうどうきをおしえてください。', 'Bạn hãy cho biết lý do ứng tuyển.'),
      turn('Ứng viên', '接客の仕事を通して、日本語をもっと上達させたいと思ったからです。', 'せっきゃくのしごとをとおして、にほんごをもっとじょうたつさせたいとおもったからです。', 'Vì tôi muốn nâng cao tiếng Nhật hơn nữa thông qua công việc tiếp khách.'),
      turn('Người phỏng vấn', '週に何日ぐらい働けますか。', 'しゅうになんにちぐらいはたらけますか。', 'Một tuần bạn làm được khoảng mấy ngày?'),
      turn('Ứng viên', '学校があるので、週に３日、夕方から働けます。', 'がっこうがあるので、しゅうにみっか、ゆうがたからはたらけます。', 'Vì còn đi học nên tôi làm được 3 ngày một tuần, từ chiều tối.'),
      turn('Người phỏng vấn', '前にアルバイトの経験はありますか。', 'まえにアルバイトのけいけんはありますか。', 'Trước đây bạn đã có kinh nghiệm làm thêm chưa?'),
      turn('Ứng viên', 'はい、ベトナムのカフェで１年間働いていました。', 'はい、ベトナムのカフェでいちねんかんはたらいていました。', 'Có, tôi đã làm ở một quán cà phê tại Việt Nam trong một năm.'),
      turn('Người phỏng vấn', '分かりました。結果は来週メールで連絡します。', 'わかりました。けっかはらいしゅうメールでれんらくします。', 'Tôi hiểu rồi. Kết quả chúng tôi sẽ báo qua email vào tuần sau.'),
    ],
    vocabularies: [
      word('面接', 'めんせつ', 'phỏng vấn'),
      word('志望動機', 'しぼうどうき', 'lý do ứng tuyển'),
      word('接客', 'せっきゃく', 'tiếp khách'),
      word('経験', 'けいけん', 'kinh nghiệm'),
      word('応募', 'おうぼ', 'ứng tuyển'),
      word('結果', 'けっか', 'kết quả'),
      word('連絡', 'れんらく', 'liên lạc'),
      word('上達', 'じょうたつ', 'tiến bộ'),
    ],
  },
  {
    title: 'Tình huống: Kể bệnh sử khi đi khám',
    level: 'N3',
    order: 4,
    situation: 'hospital',
    type: 'Tình huống',
    description: 'Trả lời bác sĩ về bệnh đã từng mắc, thuốc đang dùng và dị ứng.',
    can_do_goals: [
      'Kể được bệnh đã từng mắc và phẫu thuật đã làm',
      'Nói được loại thuốc mình đang dùng',
      'Báo được với bác sĩ mình bị dị ứng gì',
    ],
    dialogue: [
      turn('Bác sĩ', '今までに大きな病気をしたことはありますか。', 'いままでにおおきなびょうきをしたことはありますか。', 'Từ trước đến nay anh/chị đã từng mắc bệnh gì nặng chưa?'),
      turn('Bệnh nhân', '５年前に胃の手術を受けました。', 'ごねんまえにいのしゅじゅつをうけました。', 'Năm năm trước tôi đã phẫu thuật dạ dày.'),
      turn('Bác sĩ', '今、飲んでいる薬はありますか。', 'いま、のんでいるくすりはありますか。', 'Hiện anh/chị có đang uống thuốc gì không?'),
      turn('Bệnh nhân', '血圧の薬を毎朝飲んでいます。', 'けつあつのくすりをまいあさのんでいます。', 'Tôi uống thuốc huyết áp mỗi sáng.'),
      turn('Bác sĩ', 'アレルギーはありますか。', 'アレルギーはありますか。', 'Anh/chị có bị dị ứng gì không?'),
      turn('Bệnh nhân', '卵を食べると、体がかゆくなります。', 'たまごをたべると、からだがかゆくなります。', 'Hễ ăn trứng là người tôi bị ngứa.'),
      turn('Bác sĩ', '分かりました。念のため、血液検査をしておきましょう。', 'わかりました。ねんのため、けつえきけんさをしておきましょう。', 'Tôi hiểu rồi. Để cho chắc, mình làm xét nghiệm máu luôn nhé.'),
    ],
    vocabularies: [
      word('手術', 'しゅじゅつ', 'phẫu thuật'),
      word('胃', 'い', 'dạ dày'),
      word('血圧', 'けつあつ', 'huyết áp'),
      word('アレルギー', 'アレルギー', 'dị ứng'),
      word('痒い', 'かゆい', 'ngứa'),
      word('念のため', 'ねんのため', 'để cho chắc'),
      word('血液', 'けつえき', 'máu'),
      word('症状', 'しょうじょう', 'triệu chứng'),
    ],
  },
];

export default SITUATIONAL_LESSONS;
